# Generated by Django 4.2.5 on 2023-10-08 14:49

from django.db import migrations, models
import django.db.models.deletion
import playlists.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("recorded_at", models.DateField()),
                (
                    "length_in_seconds",
                    models.IntegerField(
                        validators=[playlists.validators.validate_music_length]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[playlists.validators.validate_singer_name],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "musics",
                    models.ManyToManyField(
                        related_name="playlists", to="playlists.music"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="music",
            name="singer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="playlists.singer",
            ),
        ),
    ]
